name: CI

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule: [cron: "26 4 * * *"]

jobs:
  go:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with: { go-version-file: go.mod }
      - uses: actions/cache@v4.3.0
        with:
          path: ~/.cache/go-build
          key: ${{ runner.os }}-go-${{ hashFiles('go.sum') }}
          restore-keys: ${{ runner.os }}-go-
      - run: go fmt ./...
      - run: go mod download
      - run: go mod tidy; git diff --exit-code go.mod go.sum
      - uses: golangci/golangci-lint-action@v9
      - run: go test -race ./...
