name: CI

on:
  push: {}
  pull_request: {}

jobs:
  go:
    name: Go fmt, lint, build and test
    runs-on: ubuntu-latest
    steps:
      - name: check out code
        uses: actions/checkout@v5

      - name: set up go
        uses: actions/setup-go@v6
        with:
          go-version: "1.25.1"

      - name: Cache Go modules
        uses: actions/cache@v4.3.0
        with:
          path: ~/.cache/go-build
          key: ${{ runner.os }}-go-${{ hashFiles('go.sum') }}
          restore-keys: ${{ runner.os }}-go-

      - name: go fmt
        run: go fmt ./...

      - name: get dependencies
        run: go mod download

      - name: check go.mod is tidy
        run: |
          go mod tidy
          git diff --exit-code go.mod go.sum

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v9
        with:
          version: v3.6.0

      - name: run tests
        run: go test ./...
